import { cn } from "@/utils/cn";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={cn(
            inter.className,
            process.env.NODE_ENV == "development" ? "debug-screens" : "",
          )}
        >
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
